title: William Rathje
description: |
  <a href="mailto:wrathje@berkeley.edu">email me</a>
  PhD Candidate, UC Berkeley
  Computational Social Science · Natural Language Processing  
theme: jekyll-theme-minimal

logo: /profile.jpg

