title: William Rathje
description: |
  wrathje [at] berkeley [dot] edu
  
  PhD Candidate Sociology | UC Berkeley
  
  M.S. Computer Science | Oxford
  
  M.S Sociology | Oxford
  
  B.S. Computer Science | Univ. Puget Sound
  
  B.A. English | Univ. Puget Sound
  
theme: jekyll-theme-minimal

logo: /profile.jpg

