title: William Rathje
description: -PhD Candidate Sociology, UC Berkeley
- M.S. Computer Science, Sociology, Oxford University
- B.S. Computer Science, English, University of Puget Sound
theme: jekyll-theme-minimal

logo: /profile.jpg

